# Netlify configuration for Next.js (App Router)

[build]
  command = "npm run build"

[build.environment]
  # Upgrade Node version to satisfy @supabase/supabase-js deprecation warning for <=18
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_DEBUG = "1"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# If you use custom headers or redirects, add them below. The Next plugin
# automatically configures routes for Next.js pages and API (app/ and pages/).
