# Netlify configuration for Next.js (App Router)

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs@5.8.0"

# If you use custom headers or redirects, add them below. The Next plugin
# automatically configures routes for Next.js pages and API (app/ and pages/).
